version: "3.8"
services:
  client:
    container_name: cranach_client
    build:
      context: ./
      dockerfile: Dockerfile
      target: client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    tty: true
    stdin_open: true

  server:
    container_name: cranach_server
    build:
      context: ./
      dockerfile: Dockerfile
      target: server
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: cranach_elasticsearch
    build:
      context: ./
      dockerfile: Dockerfile
      target: elasticsearch
    ports:
      - '9300:9300'
      - '9200:9200'
    restart: unless-stopped

