version: "2"
services:
  client:
    container_name: cranach_client
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    tty: true
    stdin_open: true

  server:
    container_name: cranach_server
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    container_name: cranach_mongodb
    image: mongo
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: db_user
#      MONGO_INITDB_ROOT_PASSWORD: db_password

  elasticsearch:
    container_name: cranach_elasticsearch
    build:
      context: ./
    ports:
      - '9300:9300'
      - '9200:9200'
    restart: unless-stopped

