version: "3.8"
services:
  client:
    container_name: cranach_client
    build:
      context: ./client
      target: build
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client:cached
      - /client/node_modules
    links:
      - server
    tty: true
    stdin_open: true

  server:
    container_name: cranach_server
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./server:/server:cached
      - /server/node_modules
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: cranach_elasticsearch
    build:
      context: ./
    ports:
      - '9300:9300'
      - '9200:9200'
    restart: unless-stopped

  nginx:
    container_name: cranach_nginx
    build:
      context: ./client
      target: nginx
    volumes:
      - ./var/log:/var/log/nginx:cached
    links:
      - server
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    expose:
      - "80"
      - "443"
    init: true
    tty: true